wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.50.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746821622
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.9.7
      5: 0.17.0
      6: 4.50.3
      8:
      - 5
      13: linux-x86_64
